name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim: [stable, nightly]
    steps:
      - uses: actions/checkout@v4

      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim }}

      - name: run tests
        run: make test
